# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollviewHoverDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScrollviewHoverDemo

pod 'Masonry', '~> 1.0.2'

  target 'ScrollviewHoverDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollviewHoverDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
